---
deployment:
  tasks:
    - export REPO_DIR="/home/prayinverses/api.prayinverses"
    - export APP_DIR="$REPO_DIR/api"
    - export NODE_ENV=production
    - . "/home/prayinverses/nodevenv/api.prayinverses/api/20/bin/activate"
    - export PRISMA_CLIENT_ENGINE_TYPE=binary PRISMA_CLI_QUERY_ENGINE_TYPE=binary
    - /bin/bash -lc "cd $APP_DIR && npm ci"
    - /bin/bash -lc "cd $APP_DIR && npm run build"
    - /bin/bash -lc "cd $APP_DIR && npx prisma generate"
    - /bin/bash -lc "cd $APP_DIR && npx prisma migrate deploy"
    - /bin/bash -lc "cd $APP_DIR && mkdir -p tmp && touch tmp/restart.txt"
