name: Deploy React + Tailwind to cPanel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.19.0"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: List files for debugging
        run: ls -R

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/   # ✅ Adjust if build is in a subfolder
          server-dir: /public_html/
          protocol: ftp
