name: Deploy React + Tailwind to cPanel

on:
  push:
    branches:
      - main # Change if your main branch is named differently

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.19.0" # Change to match your Node version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build
          server-dir: /public_html/
          protocol: ftp # Change to sftp if your host supports it
